
name:  build Cloud CBR Semantic sim services

on:
  push:
    branches: [ dev ]
    paths: 
      - 'api/**'
  
  workflow_dispatch:

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push  the Docker image
      uses: docker/build-push-action@v3
      with:
          push: true
          file: 'other-services/semantic-sim/Dockerfile'
          context: 'other-services/semantic-sim/'
          tags: isee4xai/isee-clood-cbr-other-semantic-sim:dev
          
  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    name: Deploy on dev platform 
    steps:
      - uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_DEV }}
          webhook_secret: ${{ secrets.WEBHOOK_TOKEN_DEV }}
          data: '{"DOCKER_SERVICE":"cloodcbr-other-semantic-sim"}'
          webhook_type: 'json-extended'
          
